# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chris Baume
author: Chris Baume
author_link: http://baume.uk
author_description: My name is Chris
email: chris@baume.uk
description: > # this means to ignore newlines until "baseurl:"
  This is an awesome description of my site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://baume.uk" # the base hostname & protocol for your site

# Picturefill
# A responsive image polyfill: http://scottjehl.github.io/picturefill/
picturefill: false

# Typography
# To use, publish a kit and enter the ID here. If you do not wish to use Typekit,
# leave this ID blank
typekit_kit_id: kwf5dox

# Build settings
gems: [jekyll-paginate, jekyll-youtube]
markdown: kramdown
permalink: /notes/:year/:month/:day/:title/
highlighter: rouge

# Pagination
paginate: 3
paginate_path: "/notes/page:num/"

# Sass
sass:
    style: :compressed

collections:
  publications:
    output: false
  presentations:
    output: false
  media:
    output: false
  projects:
    output: true
  notes:
    output: true
  travel:
    output: true
